### ISSUE TITLE
Why code snippets at http://baconjs.github.io/api.html are editable?

### ISSUE THREAD

**Issue by rpominov** [baconjs/baconjs.github.io#26]
And also text selection seems to not work in code snippets.

**Comment by phadej** [comment]
Short answer: because I'm lazy :(
Long answer: they are codemirror instances to get code highlighting. Have to integrate highlight.js for non-executable examples. But would like the theme to be the same. PR's welcome.

**Comment by pozadi** [comment]
I'd better leave it without highlighting than using codemirror which makes code editable, just imho ;)

**Comment by erdeszt** [comment]
Code mirror has a readOnly mode which seems an easier change than adopting highlight.js(see: https://codemirror.net/doc/manual.html). Should I create a PR?

**Comment by raimohanska** [comment]
At least text selection now works thanks to @villevuor
