### ISSUE TITLE
non-idiomatic/bad code in tutorial

### ISSUE THREAD

**Issue by Sequoia** [baconjs/baconjs.github.io#32]
``` javascript
function textFieldValue(textField) {
    function value() { return textField.val() }
    return textField.asEventStream("keyup").map(value).toProperty(value())
}
​
username = textFieldValue($("#username input"))
fullname = textFieldValue($("#fullname input"))
```

This code (the `value` function bit) from the tutorial seems very non-functional-y. The `value` function doesn't take any input at all, in that sense there's not really a point to mapping to it, or at the very least it's a bad example of how `map` should be used.

Enjoying the tutorial otherwise.

**Comment by Sequoia** [comment]
```
function getval(e){ return e.target.value; }
```

**Comment by phadej** [comment]
Nice spot. You can also do `.map(".target.value")`, which is a bit more concise. Can you make a PR for the fix?

**Comment by Sequoia** [comment]
Will do! I'll def. use my simple function & also the `'.method'` style if I think I can fit it in concisely.
