### ISSUE TITLE
Wrong link in documentation: Bacon.mergeAll() -> observable.merge()

### ISSUE THREAD

**Issue by alinnert** [baconjs/baconjs.github.io#40]
https://baconjs.github.io/api2.html#bacon-mergeall

This part of the documentation says:

> merges given array of EventStreams or Properties. Returns an EventStream. See merge

The last word "merge" is a link containing the anchor #observable-merge. This anchor doesn't exist though. But there's an anchor called [#stream-merge](https://baconjs.github.io/api2.html#stream-merge).

I don't know, is this the intended target of the link behind "merge"?

This issue is present in both v1 and v2 api documentation.

**Comment by raimohanska** [comment]
Thanks. Fixed!
