### ISSUE TITLE
Sleeker URL

### ISSUE THREAD

**Issue by anttiharju** [baconjs/baconjs.github.io#57]
[js.org](https://js.org/) provides free URLs for projects with "reasonable content with a clear connection to JavaScript".

So instead of [baconjs.github.io](https://baconjs.github.io) this project could have [bacon.js.org](https://bacon.js.org), which looks pretty neat to me. Getting the subdomain should be a non-issue per their documented [exceptions](https://github.com/js-org/js.org/wiki/Subdomain-Determination#exceptions).

I think [the configuration](https://github.com/js-org/js.org?tab=readme-ov-file#step-3) ("you will need to use the UI") would have to be done by someone with access to the settings of this repo. Therefore a baconjs org member would probably have to do it. Happy to help if given a go-ahead and set it up completely if given access to the settings.

🥓

**Comment by raimohanska** [comment]
For me this project is in a minimal maintenance mode and I don't personally see a point in setting up a new URL for it. I don't recommend adopting the library at this point and would rather not do anything to spark any new interest in it if you know what i mean.

Thanks for the suggestion though, that's appreciated!

**Comment by anttiharju** [comment]
Makes sense, closing. Cheers!
